config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :restaurants do
    resources :comments
  end
  root 'restaurants#index'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  has_ancestry

  belongs_to :restaurant, inverse_of: :comments

  validates :restaurant, presence: true
end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base
  has_many :comments, inverse_of: :restaurant

  def to_s
    name
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def index
    @comments = Comment.where(restaurant_id: params[:restaurant_id])
  end

  # remember this for your project
  def create
    @comment = Comment.create(comment_params.merge(restaurant_id: params[:restaurant_id]))
  end

  def comment_params
    # I DONT NEED PARENT ID
    params.required(:comment).permit(:body, :author, :parent_id)
  end
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  def index
    @restaurants = Restaurant.all
  end

  def show
    @restaurant = Restaurant.find(params[:id])
    @comments = @restaurant.comments
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.haml
!!!
%html{:lang => "en"}
  %head
    %meta{:charset => "utf-8"}
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}
    %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}
    %title= content_for?(:title) ? yield(:title) : "Untitled"
    = stylesheet_link_tag    "application"
    = javascript_include_tag "vendor/modernizr"

    = csrf_meta_tags
  %body
    %nav.top-bar.foundation-bar{data: {topbar: ''}}
      %ul.title-area
        %li.name
          %h1
            %a{:href => "/"}
              Reilly Restaurants
      %section.top-bar-section
        %ul
          %li
            = link_to 'manage restaurants', rails_admin_path
    .row
      .large-12.columns
        = yield
    = javascript_include_tag "application"

app/views/restaurants/index.html.haml
%h1 Restaurants
%ul
  - @restaurants.each do |restaurant|
    %li=link_to restaurant, restaurant_path(restaurant)

app/views/restaurants/show.html.haml
.row
  %h1= @restaurant.name
.row
  .columns.medium-6
    %p= @restaurant.description
  .columns.medium-6
    %h3 Comment
    = react_component('CommentSection', comments: raw(render template: 'comments/index.json.jbuilder'))
    / - @comments.each do |comment|
    /   = react_component('Comment', {author: comment.author, body: comment.body, rank: comment.rank})